# Generated by Django 6.0.4 on 2026-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
