# Generated by Django 6.0.4 on 2026-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_background_book_description_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
